os: linux
dist: trusty
sudo: false
language: node_js
node_js: '9.11.1'
cache:
  yarn: true
  bundler: true
  directories:
    - node_modules
before_install:
  - '[ ! -z "$BUILD_CONFIG" ] && echo "$BUILD_CONFIG" > "build-config.json" || :'
install:
  - bin/setup
jobs:
  include:
    - stage: test
      env: TEST=lint-js
      script: yarn run lint-js
    - stage: test
      env: TEST=test-js
      script: yarn run test-js
    - stage: build
      env: BUILD=build-ios
      if: head_branch IN (master, develop) AND (type IS pull_request OR tag IS present)
      os: osx
      osx_image: xcode9.3
      script: 'if [[ "$TRAVIS_BRANCH" =~ ^(master|develop)$ ]]; then bin/ci-build-ios; else echo "Skipping build on non-primary branches"; fi'
