# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

require_relative 'override_print_table'
require_relative 'parse_raw_args'

default_platform(:ios)

platform :ios do
  desc "Build (archive) the app"
  lane :build do
    begin
      sh("../../scripts/generate-and-write-ios-config")
      sh("../../scripts/start-background-packager")
      create_keychain(name: "temp_code_sign", unlock: true, timeout: false, password: "pwd")
      sync_code_signing(keychain_name: "temp_code_sign", keychain_password: "pwd", readonly: true)
      build_app(project: "XConf.xcodeproj", scheme: "XConf", silent: true)
    ensure
      sh("../../scripts/kill-background-packager")
      delete_keychain(name: "temp_code_sign")
    end
  end

  desc "Push a new build to TestFlight"
  lane :beta do |options|
    build
    upload_to_testflight(testflight_params(options))
    # For the parameters of upload_to_testflight, see:
    # https://docs.fastlane.tools/actions/upload_to_testflight/#parameters
  end

  lane :ci_build do
    build
    upload_to_testflight(changelog: "CI build")
  end
end

def testflight_params(options)
  params = {}
  if options[:raw_args]
    args = parse_raw_args(options[:raw_args])
    params[:changelog] = args['-m'] if args['-m']
  end
  params
end
