// console.error = (...args) => {
//   // Ignore error generated by Animated.Views in react-test-renderer
//   if (args[0] && args[0].message === "Cannot read property 'getScrollableNode' of null") return null
//   return console.error(...args)
// }
